export const VOUCHER_TYPES = ['JOURNAL', 'PAYMENT', 'RECEIPT', 'SALES', 'PURCHASE', 'CONTRA'];
export const VOUCHER_STATUSES = ['DRAFT', 'POSTED', 'CANCELLED', 'REVERSED'];
export const USER_ROLES = ['OWNER', 'MANAGER', 'ACCOUNTANT', 'VIEWER'];
